
grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  sidecar:
    dashboards:
      enabled: true
  persistence:
    enabled: true
    storageClassName: "gp2"
    size: 5Gi

prometheus:
  prometheusSpec:
    retention: "15d"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

